#!/usr/bin/env bash

alias ls='eza --icons=automatic'
alias ll='ls -lahL'
alias t='tree -C -a -I .git'
alias d='docker'
alias dc='docker compose'
alias dr='docker run --rm -it'
alias dr-amd='dr --platform=linux/amd64'
alias de='docker exec -it'
alias g='git'
alias gwr='source ~/bin/git-worktree-remove'
alias g-clean-branches='git branch --merged main | grep -v "^\*" | xargs -n 1 git branch -d'
alias v='nvim'
alias v-changed='nvim $(git dm --name-only)'
alias v-conflicts='nvim $(git diff --name-only --diff-filter=U)'
alias k='kubectl'
alias kk='k9s --kubeconfig=$HOME/.kube/contexts/$(ls $HOME/.kube/contexts | fzf)'
alias cat='bat'
alias randompw='openssl rand -base64 18'
alias cdd='cd $(find ~/code -maxdepth 4 -type d | sort -u | fzf)'
alias note='(cd /Users/mitch/code/github.com/mitchnielsen/notes && nvim .)'
alias rg='rg --ignore-file=$HOME/.config/ripgrep/.ignore'
alias code='codium'
alias cl='claude'
alias clp='claude code -p'
alias tf='terraform'
alias lg='lazygit'

alias python-venv='if [ ! -f ./.venv/bin/activate ]; then echo Creating virtualenv...; uv venv --python=3.12; fi; source .venv/bin/activate'
