local M = {}

local palettes = {
  dark = {
    fg = "#e6edf3",
    dim = "#7d8590",
    faint = "#484f58",
    subtle_bg = "#23262b",
    float_bg = "#23262b",
    border = "#30363d",
    green = "#3fb950",
    red = "#f85149",
    link = "#2f81f7",
    info = "#8b949e",
    yellow = "#d29922",
    interp = "#79c0ff",
    visual = "#264f78",
    cursor_line = "#23262b",
    search = "#5d4a1e",
    match = "#1f2733",
    error_bg = "#3a1414",
    warn_bg = "#3d2e07",
    add_bg = "#0f2c1a",
    delete_bg = "#3a1414",
    fzf_cursor = "#264f78",
  },
  light = {
    fg = "#24292f",
    dim = "#6e7781",
    faint = "#b0b8c1",
    subtle_bg = "#f6f8fa",
    float_bg = "#eeeeee",
    border = "#d0d7de",
    green = "#1a8a0e",
    red = "#a12a2a",
    link = "#0969da",
    info = "#57606a",
    yellow = "#8a5a00",
    interp = "#0550ae",
    visual = "#d8dee4",
    cursor_line = "#eaeef2",
    search = "#fbe5a0",
    match = "#eaeef2",
    error_bg = "#fdf0f0",
    warn_bg = "#fff8e5",
    add_bg = "#dafbe1",
    delete_bg = "#fbe5e1",
    fzf_cursor = "#b6e3ff",
  },
}

function M.apply(background)
  local c = palettes[background]

  vim.cmd("highlight clear")
  vim.o.background = background
  vim.g.colors_name = "clarity-" .. background

  local groups = {
    Normal = { fg = c.fg, bg = "NONE" },
    NormalFloat = { fg = c.fg, bg = c.float_bg },
    FloatBorder = { fg = c.fg, bg = c.float_bg },
    FloatTitle = { fg = c.fg, bg = c.float_bg, bold = true },
    Cursor = { fg = "NONE", bg = c.fg },
    CursorLine = { bg = c.cursor_line },
    CursorLineNr = { fg = c.fg, bold = true },
    LineNr = { fg = c.faint },
    SignColumn = { bg = "NONE" },
    FoldColumn = { fg = c.faint, bg = "NONE" },
    Folded = { fg = c.dim, bg = c.subtle_bg },
    VertSplit = { fg = c.border, bg = "NONE" },
    WinSeparator = { fg = c.border, bg = "NONE" },
    ColorColumn = { bg = c.subtle_bg },
    Visual = { bg = c.visual },
    VisualNOS = { bg = c.visual },
    Search = { bg = c.search },
    IncSearch = { bg = c.search, bold = true },
    CurSearch = { fg = "#ffffff", bg = c.link, bold = true },
    MatchParen = { bg = c.match, bold = true },
    NonText = { fg = c.faint },
    SpecialKey = { fg = c.faint },
    Whitespace = { fg = c.faint },
    EndOfBuffer = { fg = c.faint },
    Directory = { fg = c.link },
    Title = { fg = c.fg, bold = true },
    Question = { fg = c.green },
    MoreMsg = { fg = c.green },
    ErrorMsg = { fg = c.red, bold = true },
    WarningMsg = { fg = c.yellow, bold = true },
    WildMenu = { fg = c.fg, bg = c.visual },

    StatusLine = { fg = c.fg, bg = "NONE" },
    StatusLineNC = { fg = c.dim, bg = "NONE" },
    WinBar = { fg = c.fg, bg = "NONE" },
    WinBarNC = { fg = c.dim, bg = "NONE" },

    Pmenu = { fg = c.fg, bg = c.float_bg },
    PmenuSel = { bg = c.match },
    PmenuSbar = { bg = c.subtle_bg },
    PmenuThumb = { bg = c.border },

    TabLine = { fg = c.dim, bg = c.subtle_bg },
    TabLineSel = { fg = c.fg, bg = "NONE", bold = true },
    TabLineFill = { bg = "NONE" },

    Comment = { fg = c.dim },
    Constant = { fg = c.fg },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.fg },
    Boolean = { fg = c.fg, bold = true },
    Float = { fg = c.fg },
    Identifier = { fg = c.fg },
    Function = { fg = c.link },
    Statement = { fg = c.fg, bold = true },
    Conditional = { fg = c.fg, bold = true },
    Repeat = { fg = c.fg, bold = true },
    Label = { fg = c.fg, bold = true },
    Operator = { fg = c.fg },
    Keyword = { fg = c.fg, bold = true },
    Exception = { fg = c.red, bold = true },
    PreProc = { fg = c.dim },
    Include = { fg = c.fg, bold = true },
    Define = { fg = c.fg, bold = true },
    Macro = { fg = c.fg },
    PreCondit = { fg = c.fg },
    Type = { fg = c.fg },
    StorageClass = { fg = c.fg, bold = true },
    Structure = { fg = c.fg },
    Typedef = { fg = c.fg },
    Special = { fg = c.fg },
    SpecialChar = { fg = c.green },
    Tag = { fg = c.link },
    Delimiter = { fg = c.fg },
    SpecialComment = { fg = c.dim, bold = true },
    Debug = { fg = c.red },
    Underlined = { fg = c.link, underline = true },
    Error = { fg = c.red, bold = true },
    Todo = { fg = c.info, bold = true },

    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.red },
    ["@comment.warning"] = { fg = c.yellow },
    ["@comment.todo"] = { fg = c.info, bold = true },
    ["@comment.note"] = { fg = c.info },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.dim },
    ["@string.regexp"] = { fg = c.dim },
    ["@string.special"] = { fg = c.interp },
    ["@string.special.url"] = { fg = c.link, underline = true },
    ["@character"] = { link = "Character" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@function"] = { fg = c.link },
    ["@function.builtin"] = { fg = c.link },
    ["@function.call"] = { fg = c.link },
    ["@function.macro"] = { fg = c.link },
    ["@function.method"] = { fg = c.link },
    ["@function.method.call"] = { fg = c.link },
    ["@constructor"] = { fg = c.link },
    ["@keyword"] = { fg = c.fg, bold = true },
    ["@keyword.function"] = { fg = c.fg, bold = true },
    ["@keyword.return"] = { fg = c.fg, bold = true },
    ["@keyword.operator"] = { fg = c.fg, bold = true },
    ["@keyword.type"] = { fg = c.fg, bold = true },
    ["@keyword.modifier"] = { fg = c.fg, bold = true },
    ["@keyword.conditional"] = { fg = c.fg, bold = true },
    ["@keyword.repeat"] = { fg = c.fg, bold = true },
    ["@keyword.exception"] = { fg = c.red, bold = true },
    ["@keyword.import"] = { fg = c.fg, bold = true },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.interp, italic = true },
    ["@variable.parameter"] = { fg = c.fg },
    ["@variable.member"] = { fg = c.fg },
    ["@property"] = { fg = c.fg },
    ["@type"] = { fg = c.fg },
    ["@type.builtin"] = { fg = c.fg, bold = true },
    ["@type.definition"] = { fg = c.fg },
    ["@constant"] = { fg = c.fg },
    ["@constant.builtin"] = { fg = c.fg, bold = true },
    ["@constant.macro"] = { fg = c.fg },
    ["@module"] = { fg = c.fg },
    ["@tag"] = { fg = c.fg, bold = true },
    ["@tag.attribute"] = { fg = c.fg },
    ["@tag.delimiter"] = { fg = c.dim },
    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.bracket"] = { fg = c.fg },
    ["@punctuation.special"] = { fg = c.interp },
    ["@markup.heading"] = { fg = c.fg, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.link"] = { fg = c.link },
    ["@markup.link.label"] = { fg = c.link },
    ["@markup.link.url"] = { fg = c.link, underline = true },
    ["@markup.raw"] = { fg = c.green },
    ["@markup.list"] = { fg = c.fg },
    ["@diff.plus"] = { fg = c.green },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.info },

    ["@lsp.type.namespace"] = { fg = c.fg },
    ["@lsp.type.type"] = { fg = c.fg },
    ["@lsp.type.class"] = { fg = c.fg },
    ["@lsp.type.enum"] = { fg = c.fg },
    ["@lsp.type.interface"] = { fg = c.fg },
    ["@lsp.type.struct"] = { fg = c.fg },
    ["@lsp.type.parameter"] = { fg = c.fg },
    ["@lsp.type.variable"] = { fg = c.fg },
    ["@lsp.type.property"] = { fg = c.fg },
    ["@lsp.type.function"] = { fg = c.link },
    ["@lsp.type.method"] = { fg = c.link },
    ["@lsp.type.macro"] = { fg = c.fg },
    ["@lsp.type.decorator"] = { fg = c.fg },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.dim },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.dim, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.error_bg },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.warn_bg },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.subtle_bg },
    DiagnosticVirtualTextHint = { fg = c.dim, bg = c.subtle_bg },

    DiffAdd = { bg = c.add_bg },
    DiffChange = { bg = c.subtle_bg },
    DiffDelete = { bg = c.delete_bg },
    DiffText = { bg = c.visual },
    Added = { fg = c.green },
    Changed = { fg = c.info },
    Removed = { fg = c.red },
    MiniDiffSignAdd = { fg = c.green },
    MiniDiffSignChange = { fg = c.info },
    MiniDiffSignDelete = { fg = c.red },

    TreesitterContext = { bg = c.subtle_bg },
    TreesitterContextLineNumber = { fg = c.dim, bg = c.subtle_bg },
    MiniCursorword = { bg = c.match },
    MiniCursorwordCurrent = { bg = c.match },
    MiniStarterHeader = { fg = c.dim },
    MiniStarterFooter = { fg = c.dim },
    MiniStarterItem = { fg = c.fg },
    MiniStarterItemBullet = { fg = c.faint },
    MiniStarterItemPrefix = { fg = c.link },
    MiniStarterQuery = { fg = c.link, bold = true },
    MiniStarterCurrent = { bg = c.cursor_line },
    MiniStarterSection = { fg = c.dim, bold = true },
    MiniStatuslineInactive = { fg = c.dim },
    MiniFilesNormal = { fg = c.fg, bg = c.float_bg },
    MiniFilesBorder = { fg = c.fg, bg = c.float_bg },
    MiniFilesTitle = { fg = c.fg, bg = c.float_bg, bold = true },
    MiniFilesCursorLine = { bg = c.match },
    MiniFilesDirectory = { fg = c.link },
    MiniFilesFile = { fg = c.fg },
    MiniClueBorder = { fg = c.fg, bg = c.float_bg },
    MiniClueTitle = { fg = c.fg, bg = c.float_bg, bold = true },
    MiniClueDescGroup = { fg = c.link },
    MiniClueDescSingle = { fg = c.fg },
    MiniClueNextKey = { fg = c.link, bold = true },
    MiniTrailspace = { bg = c.delete_bg },

    FzfLuaNormal = { fg = c.fg, bg = c.float_bg },
    FzfLuaBorder = { fg = c.fg, bg = c.float_bg },
    FzfLuaTitle = { fg = c.fg, bg = c.float_bg, bold = true },
    FzfLuaPreviewNormal = { fg = c.fg, bg = c.float_bg },
    FzfLuaPreviewBorder = { fg = c.fg, bg = c.float_bg },
    FzfLuaPreviewTitle = { fg = c.fg, bg = c.float_bg, bold = true },
    FzfLuaCursorLine = { bg = c.fzf_cursor },
    FzfLuaCursorLineNr = { fg = c.fg, bg = c.fzf_cursor, bold = true },
    FzfLuaSearch = { fg = c.link },
    FzfLuaHeaderBind = { fg = c.link },
    FzfLuaHeaderText = { fg = c.dim },
    FzfLuaFzfNormal = { fg = c.fg, bg = c.float_bg },
    FzfLuaFzfGutter = { bg = c.float_bg },
    FzfLuaFzfHeader = { fg = c.dim },
    FzfLuaFzfInfo = { fg = c.dim },
    FzfLuaFzfPointer = { fg = c.link },
    FzfLuaFzfPrompt = { fg = c.link },
    FzfLuaFzfMatch = { fg = c.link },

    BlinkCmpMenu = { fg = c.fg, bg = c.float_bg },
    BlinkCmpMenuBorder = { fg = c.fg, bg = c.float_bg },
    BlinkCmpMenuSelection = { bg = c.match },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelMatch = { fg = c.link, bold = true },
    BlinkCmpKind = { fg = c.dim },
    BlinkCmpDoc = { fg = c.fg, bg = c.float_bg },
    BlinkCmpDocBorder = { fg = c.fg, bg = c.float_bg },
  }

  for group, opts in pairs(groups) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

return M
