# vim: set ft=ruby:

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision 'docker'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
    vb.memory = '8192'
    vb.customize ['modifyvm', :id, '--audio', 'none']
    vb.customize ['modifyvm', :id, '--nestedpaging', 'on']
  end
end
