# vim: set ft=ruby:

Vagrant.configure('2') do |config|
  # Host OS
  config.vm.box = 'ubuntu/focal64'
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.hostname = 'devenv'
  config.vm.define 'devenv'
  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 4
    vb.memory = '16384'
  end

  # Networking
  config.vm.network 'private_network', ip: '192.168.33.10'

  # Plugins
  config.vagrant.plugins = ['vagrant-vbguest']

  # Files
  config.vm.synced_folder '/Users/mnielsen/code', '/home/vagrant/code'
  config.vm.synced_folder '/Users/mnielsen/dotfiles', '/home/vagrant/dotfiles'

  # Configuration
  config.vm.provision 'shell', name: 'bootstrap_root', path: './bootstrap_root.sh', privileged: true
  config.vm.provision 'shell', name: 'bootstrap', path: './bootstrap.sh', privileged: false
  config.vm.provision 'file', source: '~/.gitconfig', destination: '/home/vagrant/.gitconfig'
  config.vm.provision 'file', source: 'sshconfig', destination: '~/.ssh/config'
  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa.host"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.host.pub"
  config.vm.provision "file", source: "~/.ssh/known_hosts", destination: "~/.ssh/known_hosts.host"
  config.vm.provision 'docker'
end
