[tools]
1password = "2.35.0-beta.01"
clickhouse = "latest" # brew cask is deprecated
node = "lts"

[settings]
trusted_config_paths = ['~/code', '~/dotfiles']
idiomatic_version_file_enable_tools = ["node"]
